version: 2
sources:
  - name: hubspot
    database: fivetran_database
    freshness: 
      warn_after: {count: 12, period: hour}
    loaded_at_field: _hubspot_synced
    schema: hubspot
    tables:
      - name: contacts